---
title: "Code Book"
author: "Mohsin Ali"
date: "4/3/2020"
output: pdf_document
---
The **run_analysis.R** script performs data prepration using steps that were given in the project instructions in Getting and cleaning data course on coursera.

# 1. Loading Data and Merge the training and the test sets to create one data set

+ **activity_data** <- **activitylabels.txt** : 6 rows, 2 columns.
List of activities performed when the corresponding measurements were taken and its codes (labels)

+ **data_columns_names** <- **features.txt** : 561 rows,  2 columns. The features comes from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ.

+ **subject_test** <- **test/subject_test.txt** : 2947 rows, 1 column
contains test data of 9/30 volunteer test subjects being observed

+ **subject_train <- test/subject_train.txt** : 7352 rows, 1 column
contains train data of 21/30 volunteer subjects being observed

+ **x_train <- test/X_train.txt** : 7352 rows, 561 columns
contains recorded features train data

+ **x_test <- test/X_test.txt** : 2947 rows, 561 columns
contains recorded features test data

+ **train_data_y** <- **y_train.txt** : 7352 rows, 1 column. contains train data of activities’code labels

+ **y_test <- test/y_test.txt** : 2947 rows, 1 columns
contains test data of activities’code labels

# 2. Merges the training and the test sets to create one data set

+ **merged_x**: 10299 rows, 561 columns. it is obtained by merging **x_test** and **x_train** using bind_rows()

+ **merged_y**: 10299 rows, 1 columns. it is obtained by merging **y_train** and **y_test** using bind_rows()

+ **merged_data_subject**: 110299 rows, 1 columns. it is obtained by merging **subject_train** and **subject_test** using bind_rows()

+ **merged_data**: 10299 rows, 563 columns. it is obtained by merging **merged_x**,**merged_y** and **merged_data_subject** using bind_cols()

# 3. Uses descriptive activity names to name the activities in the data set

+ Entire numbers in **code** column of the **merged_data** replaced with corresponding activity taken from second column of the activities variable

# 4.  Extracts only the measurements on the mean and standard deviation for each measurement.

+ **tidy_data** : 10299 rows, 88 columns is created by subsetting **merged_Data**, selecting only columns: subject, code and the measurements on the mean and standard deviation (std) for each measurement

# 5. Appropriately labels the data set with descriptive variable names.

+ **code** column in **tidy_data** renamed into activities
+ All **Acc** in column’s name replaced by **Accelerometer**
+ All **Gyro** in column’s name replaced by **Gyroscope**
+ All **BodyBody** in column’s name replaced by **Body**
+ All **Mag** in column’s name replaced by **Magnitude**
+ All **start** with character f in column’s name replaced by **Frequency**
+ All **start** with character t in column’s name replaced by **Time**

# 6. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject

+ **FinalData** (180 rows, 88 columns) is created by sumarizing **tidy_Data** taking the means of each variable for each activity and each subject, after groupped by subject and activity.
Export **FinalData** into **FinalData.txt** file.
